### ISSUE TITLE
Ready for Grading Week 2 Assignment

### ISSUE THREAD

**Issue by Mrowin94** [madisoncollege-it-programs/python-scripting-mrowin#1]
There are way simpler things than github these days... is this really still used heavily?

**Comment by cethenmc** [comment]
Hi, Mitchell.  I would like to see you redo Week 2, Assignment #1.  I don't see a check in that included a filetorevert file.  Please consider redoing the assignment in the week2 folder where the next assignment is located, and reply to this issue ticket when complete. ~Chris

**Comment by Mrowin94** [comment]
I don't know what you want me to do, If i forcefully revert to the first commit im pretty sure its going to clear everything wont it?
Anyways I created a new text file, committed it, pushed it back to before i committed it, 
I think this is actually the fourth time i have done this git lab now because the first few times i glitched it out somehow

**Comment by cethenmc** [comment]
Hi, Mitchell.  I am sorry, I saw this in drafts without hitting send.

Do all of the steps, but issue the commit to the latest point in your tree before placing a filetorevert.txt.  Follow the same steps, but pick the hash of the latest commit before you committed this change.

Thanks.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by Mrowin94** [comment]
It should be good now, do i need to submit anything in blackboard for these? I was assuming no, it says we submit in github and says nothing about blackboard

**Comment by cethenmc** [comment]
Thanks, Mitchell.  You are correct-Nothing through blackboard for the scripts.  Hopefully, I will be able to check it out tomorrow.

Kind regards,

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
Way to stick with it!  Looks good!
