### ISSUE TITLE
Week 9 Functions done

### ISSUE THREAD

**Issue by Mrowin94** [madisoncollege-it-programs/python-scripting-mrowin#12]
was it suppose to be this easy?
I feel like i missed something, the beginning of the assignment looks like pointers instead of directions

**Comment by cethenmc** [comment]
Hi, Mitchell.  Please re-watch the videos and tie the concepts to the checklist below.  Please book me should you have questions.  You will want to redo this one, as functions will be everywhere on the final.  For now, 4 out of 8.  To help you, the unchecked boxes were unfulfilled requirements.

![image](https://user-images.githubusercontent.com/112707666/202344780-133b605b-51cc-4e9a-8221-68af1625e4ce.png)

I will also add that if the tempconversion.py was intended to be run through the "main()" function:  "Script 2 - Temp Conversion (**Main**)."  You may consider modifying your tempconversion.py script or creating another (tempconversion2.py) where it will use __name__ to ensure the main() function runs.  Your main() function can be the code you made in tempconversion.py.

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208682216-f895433b-965c-4517-ba43-84a6c1da31a1.png)
