### ISSUE TITLE
Week 11 Argparse finished

### ISSUE THREAD

**Issue by Mrowin94** [madisoncollege-it-programs/python-scripting-mrowin#14]
Umm, if im not mistaken this ended up being us practically copying "[Sample Code] Argument Parser" 1:1?
I guess i figured out how the syntax works making so many typing mistakes

**Comment by cethenmc** [comment]
The goal is to become well-acquainted with the various attributes.  Some very nice work there.  I include a picture of a few missed things (note, I am not docking the two small circles as they were just simple typos, but if you resubmit corrections, perhaps you can get rid of those two less-than signs).  You scored a 6 of 8 for now.

The basic argument missed the mark slightly.  Also, the int is not set to required.  If you run anything besides help or version, you should err if you don't provide an -i with an int.

We hinted at one of the slides to determine how to print the four arguments.  There is more printing than the four arguments you were asked to print.

Please respond to this ticket if you intend to keep the 6 out of 8, or reply when the resubmitted file is ready for re-grading.

Thanks.

Chris

**Comment by cethenmc** [comment]
Sorry, I realized just now, that I never provided a picture.  Let me know if you would like to lock in the score.  I don't want to leave these Issue Tickets open if you don't intend to submit corrections.  Thanks.  Chris

![image](https://user-images.githubusercontent.com/112707666/203686459-6d7a4ca4-7ba0-41f1-a772-cef6d6fe565e.png)
