### ISSUE TITLE
Week 12 Networking finished

### ISSUE THREAD

**Issue by Mrowin94** [madisoncollege-it-programs/python-scripting-mrowin#15]

**Comment by cethenmc** [comment]
7 out of 8.  One was written in bytecode, so they are not the same file.  Please let me know if you will resubmit or would like to keep a 7 out of 8 by responded to this issue ticket comment.

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208682630-72e8cea7-578e-4ab8-8fa3-b984a5daa22d.png)
