### ISSUE TITLE
Week 13 Interacting with a Website Finished

### ISSUE THREAD

**Issue by Mrowin94** [madisoncollege-it-programs/python-scripting-mrowin#16]

**Comment by cethenmc** [comment]
I give full credit for both (8 out of 8).  However, the directions were unclear when it asked to get every link; it also wanted the 'href' values.  With the rules being unclear, I accept the link name you provide.  I would also take just the links.  In an ideal world, I would see both.  Please change your print statement to:

print(f"{link.text}:  {link.get('href')}")

No need to resubmit, but it may be good to have it for you to reference back to. 

Likewise, there is a quicker way to get the title, as well:      print(soup.title.text) 

You should not have looped for finding the title.  

You still fulfilled the requirements so gave you full credit.
