### ISSUE TITLE
Ready for Grading, second week 2 assignment!

### ISSUE THREAD

**Issue by Mrowin94** [madisoncollege-it-programs/python-scripting-mrowin#2]
Assuming we wanted the author and description commented out in the script file

**Comment by cethenmc** [comment]
Hi, Mitchell.  I would like you to update your script so you can run it from the command line.

Your first line should always be the following for your scripts. In this way, if you are running from the command line it will know what interpreter to use. Will you please add this line to the top of your first-script.py code?

#!/usr/bin/env python3

Recall from the videos, you may also need to issue a chmod command to modify the rights to make it executable.

chmod u+x first-script.py

After this, you can execute from the command line.

./first-script.py

Please be so kind as to resubmit it, so...
    1. modify the file in NetLab with the added line at the top.
    2. update the file to be executable.
    3. add the file to staging (git add .)
    4. commit the file to your local repo. (git commit -m "changes requested to run from command line")
    5. push to the git hub repository (git push)
    6. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by Mrowin94** [comment]
completed, i may have committed it without that wording though, id have to edit something random to commit it again, dont know if it matters

**Comment by cethenmc** [comment]
Nice work, Mitchell!
