### ISSUE TITLE
String Formatting Ready For Grading!

### ISSUE THREAD

**Issue by Mrowin94** [madisoncollege-it-programs/python-scripting-mrowin#3]
Going back to fix the first two now, I assumed because they executed for me they were good

**Comment by cethenmc** [comment]
This needs to be corrected.  First, it is not in week3.  It is in week2.  Second, it is not executing.  You have an error in the top row.  Compare the top line of this file to your first-script.py file, and you should find this issue quickly.

Beginning no later than the 5th item, you should be applying the lesson to use the formatted string with the colon, fill character, alignment, data type on all of these.  You want to challenge yourself to make these lines of code shortest in length that you can, using what you were taught in that lesson.  Don't use the round function at all in this assignment.  Also, when you get to #12 and #13 it may make it easier if you have the assignment Word document downloaded, so you can count the true number of spaces.  In 12 and 13 you should not have that many dollar signs and spaces manually entered.  Finally, just at a glance, I don't want to see varBlue ten times in a row.  Once is enough for that line.

Please take another shot, and reply to this Issue when complete and re - pushed to git hub.

**Comment by Mrowin94** [comment]
updated, its in week3 folder now

**Comment by cethenmc** [comment]
Hi, Mitchell.  I will record 5 out of 8 on this one.  However, feel free to resubmit again correcting some issues.
#3 Capitalization issue
#5-7 Include the square brackets
#12-13 Got everything correct inside the square brackets, but I recommended you download the word document and count spaces.  Do you notice space between the closing bracket and the opening into the next color?  ][

Thanks.

Chris

**Comment by Mrowin94** [comment]
I added the brackets to 5,6 & 7. By capitalization issue all i can see is i had the I lower case.
And 13 I thought those spaces were intended.
What word document can i download into netlab? is there a link? I open it up in the built in linux word document normally because coding in terminal is a pain

**Comment by cethenmc** [comment]
Hi Mitchell.  You almost got them all.  I am letting the following slide.

- 12 through 13 are still missing a space between each ] and [
- 14 you left out a space before the word Second and Third

< [$$$Red$$$$][$$Green$$$][$$$Blue$$$]
< [   deR    ][  Green   ][   eulB   ]
< First Color:[Red]Second Color:[Green]Third Color:[Blue]
---
> [$$$Red$$$$] [$$Green$$$] [$$$Blue$$$]
> [   deR    ] [  Green   ] [   eulB   ]
> First Color:[Red] Second Color:[Green] Third Color:[Blue]
