### ISSUE TITLE
week 5 file data interactions finished

### ISSUE THREAD

**Issue by Mrowin94** [madisoncollege-it-programs/python-scripting-mrowin#5]
So between all of the reading, slides and videos it didn't seem to match up very well with what the assignment was...
I'm assuming for the third and final part of the assignment using a loop counter variable was intended?

I had to do a lot of tweaking because for some reason multiple different ways i was doing it was actually leaving out like 40 characters in the document, i think it may have been not counting spaces or something.

But my final revision is getting the correct number.

Can you use if then functions in python? for example, loop through the document and change all specific words to a different word like microsoft words find and replace?

**Comment by cethenmc** [comment]
Hi Mitchell - The first two parts are fine.  The third is not completed correctly.  Additionally, you are not following the instruction in #3 "save the full file contents one line at a time to a variable."  Your reason could be acceptable, but you did not show that with your choice in the work.  You also left a print of the type() when it was not requested.  I will record 6 of 8 in the grade book.  However, please feel free to fix it to get full credit.  Also, feel free to reach out if you have questions.  You may book me through Instructor Contact on Blackboard.  If those times don't work, reach out via email telling me they don't work and we can try for another time.  Thanks. ~Chris

**Comment by cethenmc** [comment]
Hi Mitchell - Please book me if you are still struggling with #3.

**Comment by cethenmc** [comment]
Hi, Mitchell.  These hints helped other for the third.  If you prefer, you could you see if there is a time to walk through it in Bookings? If you cannot find a time that works, let me know via email, and we can try to find another. If you want to try it again on your own before then, please consider these hints: 

don't use any read functions except for readline (and you will likely use this twice). 

use two different variables, one for the single line output of the readline(), and one for the cumulative collection of readline() outputs. 

calculate the length outside of the loop on the cumulative collection (now, I also won't dock if you calculate each line and keep adding it to a count like some have done, but that is more work for your script than necessary).

**Comment by cethenmc** [comment]
6 out of 8 locked in.  Closing ticket.
