### ISSUE TITLE
Lab Dictionaries Week 7 Completed

### ISSUE THREAD

**Issue by Mrowin94** [madisoncollege-it-programs/python-scripting-mrowin#8]

**Comment by cethenmc** [comment]
Hi, Mitchell.  For now, I will record a 7 of 8 in the grade book.  Will you please correct 6 and 7 to use flow control to print if server 2 or 10  is found or not for full credit?

I get what you are doing for checking the existence of server 2 and server 10.  However, it is not best practice for any script to render an error.

_Traceback (most recent call last):
  File "./dictionaries.py", line 12, in <module>
    server10=dictionary["server10.testlab.com"]#Testing if Server10 is in the Dictionary
KeyError: 'server10.testlab.com'_

**Comment by cethenmc** [comment]
Locked in the 7 out of 8.  Closing ticket.
